### ISSUE TITLE
config.exe in zip archive

### ISSUE THREAD

**Issue by Summi337** [tjackenpacken/taskbar-groups#32]
Hi, want to try this little app but that config.exe file makes me nervous. What's that for? Looks like malware. I downloaded a zip file from https://github.com/tjackenpacken/taskbar-groups/releases.

Thanks!

**Comment by pikent** [comment]
The config.exe file is the one that opens the app group when you click on a extension. What happens when you create a group is that the program generates the necessary config files and then copy the config.exe and creates a shortcut. It isn't malware and is part of the software. In the latest release this .exe has been removed as to me merged into the main program. You will have to wait for a future release for that to push through or you will have to build it from source.

**Comment by Summi337** [comment]
Thanks a lot for explanation!
