### ISSUE TITLE
Arguments for app

### ISSUE THREAD

**Issue by andersberglund** [tjackenpacken/taskbar-groups#34]
It would be nice to be able to add arguments to an app. E.g "autoruns -e"

**Comment by pikent** [comment]
I will look for the possibility of doing that though some UI modifications may be needed. This will most likely come after updates to customization of the UI to avoid conflicts while updating. Currently a workaround on the current release is not possible due to it not being updated for shortcuts. However if you are building from source which has the features to support shortcuts, you can create a shortcut to the application and apply the argument manually. After that you can add that shortcut to the taskbar group. Sorry for any inconvenience!

**Comment by OLLI-S** [comment]
I posted the same request in #36 because I wanted to add shortcuts for some windows features, like:
* **Windows Updates** (command: `C:\Windows\explorer.exe ms-settings:windowsupdate`)
* **Windows Store** (command: `C:\Windows\explorer.exe ms-windows-store:`)
* **Hyper-V-Manager** (command: `C:\WINDOWS\System32\mmc.exe C:\WINDOWS\System32\virtmgmt.msc`)

My plan is to add these (and other related applications) in one group and then execute all apps within this group with one click (as suggested in #35).

I know I can create lnk files for these special applications, but it should be usable and comfortable for all users.
So please allow parameters.

**Comment by pikent** [comment]
My current concern is that the icon of the physical application itself won't be the one the user would want. I guess it would be a good time to also implement ( #13 ) fully but I will have to figure out a way to adapt the current system for such uses. But yes I will consider and will be looking into allowing arguments to be added. The customization of icons will most likely come later depending on how things go during development.

**Comment by OLLI-S** [comment]
In 0.2.0.0 you allow parameters and this is working perfectly!

**Comment by tjackenpacken** [comment]
A @OLLI-S pointed out support for start arguments has been added in [the latest release!](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0)
