### ISSUE TITLE
[Feature Request] Ability to edit already created groups

### ISSUE THREAD

**Issue by MuffinLover42** [tjackenpacken/taskbar-groups#57]
Something I'm missing with the program is the ability to edit a group I've already made.
As of now, the only way to do so (that I've found) is to delete the group and make a new one.

**Comment by PikeNote** [comment]
It is coming in version 2 which is coming out very soon in the near future!

**Comment by PikeNote** [comment]
That is quite odd, you should be able to edit your groups since v0.1.4. Can you check you have the latest version and download the latest if needed from here?

https://github.com/tjackenpacken/taskbar-groups/releases

Thinking about it, there should be probably some version indicator on the application itself.

**Comment by MuffinLover42** [comment]
I just realized I had the version from the link you sent in r/software, sorry
