### ISSUE TITLE
Bug Selecting multiple shortcouts 

### ISSUE THREAD

**Issue by Jakk-y** [tjackenpacken/taskbar-groups#61]
In version 0.2 when you select several shortcouts and one of them is a windows app shortcout and  try to add them the program does strange things, sometimes it adds them as a subgroup but when you are editing the group and you select the subgroup it fails showing only one icon and throwing an exception.
PS: I love your work

**Comment by PikeNote** [comment]
I can't exactly reproduce this currently.

To confirm, this happens when you drag and drop/select multiple shortcuts with one being a Windows App Store shortcut into the application.

To help see if this is application specific, can you try other Windows App Store shortcuts and try to pin them to start and drag it into the application.

Another thing, does it work if you only drag one Windows App Shortcut at a time in?

**Comment by Jakk-y** [comment]
I have done some tests and I have realized that the problem only occurs with games, applications such as spotify or others from the microsoft store work without problems but in the games they do not work. Maybe it's because these games are downloaded from the xbox application.  When you add a single game it fails to add it and if it is selected together with other valid shortcouts it fails too.

**Comment by PikeNote** [comment]
I will look into that right away.

**Comment by PikeNote** [comment]
Found the issue and will be fixed in the next update
