### ISSUE TITLE
[Repo] Use .gitignore

### ISSUE THREAD

**Issue by Dubzer** [tjackenpacken/taskbar-groups#8]
Hi! 
Just a little tip: you can create file with name  ".gitignore" in repository, so that some junk like "bin" folder that's unrelated to source code could be filtered and won't be committed.
There's a repository from GitHub with templates: https://github.com/github/gitignore. And that one is what you need: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

And thank you for this project! Your idea is amazing.

**Comment by AnalogCyan** [comment]
Just to add to this, you'll likely have to clear the git index and re-add everything for it to start using the .gitignore since the files it's being told to ignore are already committed, so it won't apply the new rules to them.

IIRC, this can be done with these commands (after committing any pending changes and the .gitignore file):
`git rm -r --cached .`
`git add .`
`git commit`
