### ISSUE TITLE
Bug when Start TaskBar

### ISSUE THREAD

**Issue by Vlad55432** [tjackenpacken/taskbar-groups#91]
When i'm click Taskbar (Example Youtube icon), she shows about "Could not find path: C/ProgramFiles(x86) and bla bla bla... 
![d](https://user-images.githubusercontent.com/78297186/106379418-81549800-63b4-11eb-9cdc-cad3cddc0497.PNG)

When i'm create new, shows this 
![изображение](https://user-images.githubusercontent.com/78297186/106379387-4e120900-63b4-11eb-9383-1ea8d333b630.png)

**Comment by Vlad55432** [comment]
> 
> 
> When i'm click Taskbar (Example Youtube icon), she shows about "Could not find path: C/ProgramFiles(x86) and bla bla bla...
> ![d](https://user-images.githubusercontent.com/78297186/106379407-6c780480-63b4-11eb-89ac-c76130021ea9.PNG)


> When i'm create new, shows this
> ![изображение](https://user-images.githubusercontent.com/78297186/106379387-4e120900-63b4-11eb-9383-1ea8d333b630.png)

**Comment by Tw3ak3rz** [comment]
I just resolved the same issue easily so I'll tell you how.

1. First, make sure the program is closed and that you have Hidden Files and Folders showing (see below) on your Windows system, doesn't look like it is from the image you included.
 
2. Open the folder where the Taskbar Groups is located, 

3. Open the config folder, locate the folder YouTube (it looks like, might be Friends), and delete the YouTube folder. (It may be possible you'll need to add things back but the error at least should be gone). Most likely you could just edit the XML file but not being 100% sure what to leave and delete removing the entire thing as described worked for me.

 I had a Security Folder and was getting the same error so I removed the Security folder in the program and when I tried to make it again even though I didn't see it the program said it was already there so I made a new one called Security Apps. The problem was I got an error like you every time I opened the program. I went in and with Hidden Files and Folders showing could see there was still a folder named Security in the directory so I deleted it and the next time I opened the program no more error message.

If you do not know how to show hidden, this is how.

Open File Explorer from the taskbar. 

Select View > Options > Change folder and search options.

Select the View tab and, in Advanced settings, select Show hidden files, folders, and drives and OK.

**Comment by bbKaNaTdd** [comment]
Thanks for the solution. Is there any way to see the name of the programme icon when we move the mouse cursor over it?
